# -*- coding: utf-8 -*-
"""PlayGround.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15rlEiZWQJLotCCJasrc5InGUavAlkAT2
"""

"""## Train a VAE and generate diverse samples"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

class VAE(nn.Module):
    def __init__(self, input_dim, hidden_dim, latent_dim):
        super(VAE, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2_mu = nn.Linear(hidden_dim, latent_dim)
        self.fc2_logvar = nn.Linear(hidden_dim, latent_dim)
        self.fc3 = nn.Linear(latent_dim, hidden_dim)
        self.fc4 = nn.Linear(hidden_dim, input_dim)

    def encode(self, x):
        h1 = torch.relu(self.fc1(x))
        return self.fc2_mu(h1), self.fc2_logvar(h1)

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z):
        h3 = torch.relu(self.fc3(z))
        return torch.sigmoid(self.fc4(h3))

    def forward(self, x):
        mu, logvar = self.encode(x.view(-1, 784))
        z = self.reparameterize(mu, logvar)
        return self.decode(z), mu, logvar

def loss_function(recon_x, x, mu, logvar):
    BCE = nn.functional.binary_cross_entropy(recon_x, x.view(-1, 784), reduction='sum')
    KLD = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
    return BCE + KLD

# Data Loading
transform = transforms.ToTensor()
train_dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)

# Model, Optimizer
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = VAE(input_dim=784, hidden_dim=400, latent_dim=20).to(device)
optimizer = optim.Adam(model.parameters(), lr=1e-3)

# Training Loop
epochs = 20
for epoch in range(epochs):
    model.train()
    train_loss = 0
    for data, _ in train_loader:
        data = data.to(device)
        optimizer.zero_grad()
        recon_batch, mu, logvar = model(data)
        loss = loss_function(recon_batch, data, mu, logvar)
        loss.backward()
        train_loss += loss.item()
        optimizer.step()
    print(f'Epoch {epoch}, Loss: {train_loss / len(train_loader.dataset)}')

# Visualizing the Generated Sample
import matplotlib.pyplot as plt

model.eval()
with torch.no_grad():
    zs = torch.randn(64, 20).to(device)  # Sample from standard normal distribution
    sample = model.decode(zs).cpu()
    sample = sample.view(64, 1, 28, 28)

    # Plot the generated samples
    plt.figure(figsize=(8, 8))
    for i in range(64):
        plt.subplot(8, 8, i + 1)
        plt.imshow(sample[i].squeeze(), cmap='gray')
        plt.axis('off')
    plt.show()

"""## Pick a specific noise and decoder it"""

# Fixing the Latent Variable and Fine-Tuning the Decoder
fixed_z = torch.randn(1, 20).to(device)  # Fixed latent variable

generated_sample = model.decode(fixed_z)

generated_sample = generated_sample.view(28, 28).cpu().detach().numpy()
plt.imshow(generated_sample, cmap='gray')
plt.show()

"""# Fine-tune the decoder to match a specific target from the same noise"""

print(fixed_z)

## Pick a random image from the test_set as target
transform = transforms.ToTensor()
test_dataset = datasets.MNIST(root='./data', train=False, download=True, transform=transform)
test_loader = DataLoader(test_dataset, batch_size=128, shuffle=True)

for data, _ in test_loader:
    data = data.to(device)

## Plot an image from data
img_id = torch.randint(0, len(data), (1,)).item()
plt.imshow(data[img_id].view(28, 28).cpu().detach().numpy(), cmap='gray')
plt.show()

# Optimizer for decoder layers only
decoder_params = list(model.fc3.parameters()) + list(model.fc4.parameters())
decoder_optimizer = optim.Adam(decoder_params, lr=1e-3)

fine_tune_epochs = 50
for epoch in range(fine_tune_epochs):
    model.train()
    decoder_optimizer.zero_grad()
    generated_sample = model.decode(fixed_z)

    ## Assuming you have some target image or criterion to optimize against
    #target_image = torch.randn_like(generated_sample).to(device)  # Example target

    target_image = data[img_id].flatten()[None, :].to(device)

    loss = nn.functional.mse_loss(generated_sample, target_image)  # Example loss
    loss.backward()
    decoder_optimizer.step()

    if epoch%10 == 0:
      print(f'Fine-Tuning Epoch {epoch}, Loss: {loss.item()}')

# Visualizing the Generated Sample
import matplotlib.pyplot as plt

generated_sample = generated_sample.view(28, 28).cpu().detach().numpy()
plt.imshow(generated_sample, cmap='gray')
plt.show()
print(fixed_z)

"""## How does the fine-tuned decoder performs in terms of the previous diversity ?"""

model.eval()
with torch.no_grad():
    #zs = torch.randn(64, 20).to(device)  # Sample from standard normal distribution
    sample = model.decode(zs).cpu()
    sample = sample.view(64, 1, 28, 28)

    # Plot the generated samples
    plt.figure(figsize=(8, 8))
    for i in range(64):
        plt.subplot(8, 8, i + 1)
        plt.imshow(sample[i].squeeze(), cmap='gray')
        plt.axis('off')
    plt.show()